name: Build & commit PDF
on:
  push:
    branches: [main]
    paths: ['**.tex', '**.bib', '**.{png,jpg,svg,pdf,eps}']
  workflow_dispatch:
jobs:
  latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}

      - name: Compile with latexmk
        uses: xu-cheng/latex-action@v3      # maintained TeX Live image
        with:
          root_file: main.tex               # change if your root file differs
          # latexmk_use_xelatex: true       # uncomment for XeLaTeX
          # latexmk_use_lualatex: true      # uncomment for LuaLaTeX

      - name: Commit PDF
        run: |
          git config user.name  "latex-bot"
          git config user.email "actions@github.com"
          git add main.pdf
          git commit -m "CI: rebuild PDF for $GITHUB_SHA" || echo "no changes"
          git push
